"""Embed the checked-in Berry examples in the device Web UI."""

import json
import os
import re


BEGIN = "/* EXAMPLE-CATALOG-START */"
END = "/* EXAMPLE-CATALOG-END */"


def _meta(source, key):
    match = re.search(r"^#\s*@%s\s+(.+)$" % re.escape(key), source, re.MULTILINE)
    return match.group(1).strip() if match else ""


def render_js(project_dir):
    root = os.path.join(project_dir, "examples", "apps")
    rows = []
    for filename in sorted(os.listdir(root)):
        if not filename.endswith(".ax"):
            continue
        path = os.path.join(root, filename)
        with open(path, "r", encoding="utf-8") as handle:
            source = handle.read()
        fallback = filename[:-3]
        rows.append({
            "name": fallback,
            "title": _meta(source, "name") or fallback.replace("_", " ").title(),
            "desc": _meta(source, "desc"),
            "source": source,
        })
    if not rows:
        raise SystemExit("example catalog: no examples/apps/*.ax files found")
    return (
        "/* GENERATED by scripts/example_catalog.py - DO NOT EDIT BY HAND. */\n"
        "const EXAMPLE_LIBRARY="
        + json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
        + ";"
    )


def inject(project_dir, path=None):
    path = path or os.path.join(project_dir, "webui", "index.html")
    with open(path, "r", encoding="utf-8", newline="") as handle:
        html = handle.read()
    start, end = html.find(BEGIN), html.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit("example catalog: marker block is missing from %s" % path)
    block = BEGIN + "\n" + render_js(project_dir) + "\n" + END
    updated = html[:start] + block + html[end + len(END):]
    if updated == html:
        return False
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(updated)
    return True


if __name__ == "__main__":
    import sys

    root = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(__file__))
    print("example catalog: %s" % ("regenerated" if inject(root) else "already current"))
